---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        net_hostname: "{{ inventory_hostname.split('.')[0] }}"
#       Use if you want get the hostname from an FQDN
#        net_domain_name: "{{ inventory_hostname.split('.')[1:] | join('.') }}"

    - name: Set the system attributes
      net_system:
        hostname: "{{ net_hostname }}"
        domain_name: "{{ site_domain_name }}"
        name_servers: "{{ site_nameservers }}"
        domain_search: "{{ site_domain_search }}"
