---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Convert dictionary to list
      set_fact:
        vlan_list: "{{ vlan_list|default([]) + [ {'name': item.key, 'vlan_id': item.value.vlan_id, 'state': item.value.state|default('present') } ] }}"
      when: vlans is defined
      with_dict: "{{ vlans }}"

    - name: VLAN Operations
      net_vlan:
        aggregate: "{{ vlan_list }}"
      when: vlan_list is defined
